language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
after_success:
    - bash <(curl -s https://codecov.io/bash)
